Re-worked packaging to support multiple daemon instances with their own -B bind addresses. 	* BIND_ADDRESSES in /etc/default/fb-tac-plus specifies the addresses 	  that should be bound to. Each init file command then deals with 	  the fact that multiple daemons exist. 	* Changed the packaging directory for config to match current 	  deployment.

diff --git a/debian-wheezy/debian/fb-tac-plus.init b/debian-wheezy/debian/fb-tac-plus.init
--- a/debian-wheezy/debian/fb-tac-plus.init
+++ b/debian-wheezy/debian/fb-tac-plus.init
@@ -25,7 +25,7 @@ test -x $DAEMON || exit 0
 # Default options, these can be overriden by the information
 # at /etc/default/$NAME
 DAEMON_OPTS="-d 16"          # Additional options given to the server
-CONFIG_FILE="/etc/tac_plus.conf"
+CONFIG_FILE="/etc/tac_plus/tac_plus.conf"
 LOGFILE=$LOGDIR/tac_plus.log  # Server logfile
 
 # Include defaults if available
@@ -33,18 +33,6 @@ if [ -f /etc/default/$NAME ] ; then
 	. /etc/default/$NAME
 fi
 DAEMON_ARGS="$DAEMON_OPTS -C $CONFIG_FILE"
-# we need to parse the options that were handed to the daemon to check
-# what the pidfile(s) should be called - the PID is set based on the
-# last -B argument
-# we also need to give awk access to this variable - hence the export.
-export DAEMON_OPTS
-PIDEXT=`/usr/bin/awk 'BEGIN { split(ENVIRON["DAEMON_OPTS"], array, " "); for (i=1;i in array;i++) { if(array[i] == "-B"){ current=array[i+1]; }  } print current; }'`
-
-if [ "$PIDEXT" = "" ]; then
-	PIDFILE=$PIDFILEBASE
-else
-	PIDFILE=$PIDFILEBASE.$PIDEXT
-fi
 
 # Check that the user exists (if we set a user)
 # Does the user exist?
@@ -58,7 +46,6 @@ if [ -n "$DAEMONUSER" ] ; then
         exit 1
     fi
 fi
-
 
 set -e
 
@@ -77,39 +64,95 @@ running_pid() {
 running() {
 # Check if the process is running looking at /proc
 # (works for all users)
-
-    # No pidfile, probably no daemon present
-    [ ! -f "$PIDFILE" ] && return 1
-    pid=`cat $PIDFILE`
-    running_pid $pid $DAEMON || return 1
-    return 0
+    NOT_RUNNING=0
+    if [ "$BIND_ADDRESSES" != "" ]; then
+      for ADDR in $BIND_ADDRESSES; do
+        PIDFN=$PIDFILEBASE.$ADDR
+        if [ ! -f $PIDFN ]; then
+          # no pidfile, probably not running
+          NOT_RUNNING=1
+        else
+          pid=`cat $PIDFN`
+          running_pid $pid $DAEMON
+          if [ "$?" != "0" ]; then
+            NOT_RUNNING=1
+          fi
+        fi
+      done
+    else
+       if [ ! -f $PIDFILEBASE ]; then
+        NOT_RUNNING=1
+       else
+        pid=`cat $PIDFILEBASE`
+        running_pid $pid $DAEMON
+        if [ "$?" != "0"]; then
+         NOT_RUNNING=1
+        fi
+      fi
+    fi
+    return $NOT_RUNNING
 }
 
 start_server() {
 # Start the process using the wrapper
+    FAILED=0
     if check_config_quiet ; then
-         start-stop-daemon --start --quiet -m --pidfile $PIDFILE \
-                --exec $DAEMON -- $DAEMON_ARGS
-         errcode=$?
-         return $errcode
+      if [ "$BIND_ADDRESSES" != "" ]; then
+        for ADDR in $BIND_ADDRESSES; do
+          start-stop-daemon --start --quiet -m --pidfile $PIDFILEBASE.$ADDR \
+                --exec $DAEMON -- $DAEMON_ARGS -B $ADDR
+          errcode=$?
+          if [ "$errcode" != "0" ]; then
+            FAILED=1
+          fi
+        done
+      else
+        start-stop-daemon --start --quiet -m --pidfile $PIDFILEBASE \
+              --exec $DAEMON -- $DAEMON_ARGS
+      fi
     else
          return $?
     fi
-
 }
 
 stop_server() {
-    killproc -p $PIDFILE $DAEMON
+  FAILED=0
+  if [ "$BIND_ADDRESSES" != "" ]; then
+    for ADDR in $BIND_ADDRESSES; do
+      PIDFN=$PIDFILEBASE.$ADDR
+      killproc -p $PIDFN $DAEMON
+      if [ "$?" != "0" ]; then
+        FAILED=1
+      fi
+    done
+  else
+    killproc -p $PIDFILEBASE $DAEMON
     return $?
+  fi
 }
 
 reload_server() {
+    FAILED=0
     if check_config_quiet ; then
-         [ ! -f "$PIDFILE" ] && return 1
-         pid=`cat $PIDFILE` # This is the daemon's pid
-         # Send a SIGHUP
-         kill -1 $pid
-         return $?
+      if [ "$BIND_ADDRESSES" != "" ]; then
+        for ADDR in $BIND_ADDRESSES; do
+          PIDFN=$PIDFILEBASE.$ADDR
+          if [ ! -f "$PIDFN" ]; then
+            FAILED=1
+          else
+            pid=`cat $PIDFN` # This is the daemon's pid
+            # Send a SIGHUP
+            kill -1 $pid
+            if [ "$?" != "0" ]; then
+              FAILED=1
+            fi
+          fi
+        done
+      else
+        pid=`cat $PIDFILEBASE`
+        kill -1 $pid
+        return $?
+      fi
     else
          return $?
     fi
@@ -125,23 +168,54 @@ check_config_quiet() {
 	return $?	
 }
 
+kill_pid() {
+  PIDFN=$1
+  [ ! -e "$PIDFN" ] && return
+  pid=`cat $PIDFN`
+  if running_pid $pid $DAEMON; then
+    kill -15 $pid
+    # Is it really dead?
+    sleep "$DIETIME"s
+    if running_pid $pid $DAEMON ; then
+      kill -9 $pid
+      sleep "$DIETIME"
+      if running_pid $pid $DAEMON ; then
+        log_progress_msg "Cannot kill $NAME (pid=$pid)!"
+        return 1
+      fi
+    fi
+  fi
+  return 0
+}
+
 force_stop() {
 # Force the process to die killing it manually
-	[ ! -e "$PIDFILE" ] && return
-	if running ; then
-		kill -15 $pid
-	# Is it really dead?
-		sleep "$DIETIME"s
-		if running ; then
-			kill -9 $pid
-			sleep "$DIETIME"s
-			if running ; then
-				echo "Cannot kill $NAME (pid=$pid)!"
-				exit 1
-			fi
-		fi
-	fi
-	rm -f $PIDFILE
+  FAILED=0
+  if [ "$BIND_ADDRESSES" != "" ]; then
+    for ADDR in $BIND_ADDRESSES; do
+      PIDFN=$PIDFILEBASE.$ADDR
+      kill_pid $PIDFN
+      if [ "$?" != "0" ]; then
+        FAILED=1
+      else
+	      rm -f $PIDFN
+      fi
+    done
+  else
+    kill_pid $PIDFN
+    if [ "$?" != "0" ]; then
+      FAILED=1 
+    fi
+  fi
+  if [ "$FAILED" != "0" ]; then
+    log_progress_msg "couldn't kill some instances"
+    log_end_msg 1
+    exit 1
+  else
+    log_progress_msg "killed all instances"
+    log_end_msg 0
+    exit 0
+  fi
 }
 
 
